app:
  debug: true
  # 0 Panic,1 Fatal,2 Error, 3 Warn, 4 Info, 5 Debug, 6 Trace
  log_level: 6
  # 日志输出类型，0 string, 1 json
  log_output_type: 0
  # 日志输出方式，0控制台，1文件
  log_output_flag: 0
  # 日志目录
  log_path: ./runtime/log/
  # 服务端地址
  server_host: 192.168.28.124
  # 服务端控制端口
  server_port: 10010
  # 本机昵称
  local_name: 公司电脑
  # 控制端心跳时间,s为单位
  control_heartbeat_time: 30
  # 控制端重连时间，s为单位
  control_reconn_tcp_time: 5
  # 客户端唯一id所在目录
  uid_path: ./runtime/uid/